name: Check final newline

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check if all files end in newline
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check final newline
      uses: johannesvedder/check-final-newline@dev
      with:
        commit_changes: 'true'
        commit_name: 'Testbot'
